services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=nyak
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=eventostec
    volumes:
      - eventostec_pg_data:/bitnami/postgresql

volumes:
  eventostec_pg_data: